import { defineField, defineType } from 'sanity'

export const tourType = defineType({
  name: 'tour',
  title: 'Expediciones',
  type: 'document',
  groups: [
    { name: 'es', title: '🇬🇹 Español' },
    { name: 'en', title: '🇺🇸 English' },
    { name: 'general', title: 'General' },
  ],
  fields: [
    defineField({
      name: 'title',
      title: 'Nombre de la Expedición',
      type: 'string',
      group: 'es',
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: 'titleEn',
      title: 'Expedition Name (English)',
      type: 'string',
      group: 'en',
      description: 'Si lo dejas vacío, el sitio en inglés usará el nombre en español.',
    }),
    defineField({
      name: 'slug',
      title: 'URL Amigable (Slug)',
      type: 'slug',
      group: 'general',
      options: { source: 'title', maxLength: 96 },
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: 'mainImage',
      title: 'Imagen Principal',
      type: 'image',
      group: 'general',
      options: { hotspot: true },
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: 'pdfCatalogue',
      title: 'Catálogo o Información en PDF (Español)',
      type: 'file',
      group: 'es',
      options: {
        accept: '.pdf',
      },
      description: 'Sube el archivo PDF del itinerario directamente desde tu computadora.',
    }),
    defineField({
      name: 'pdfCatalogueEn',
      title: 'PDF Catalogue (English)',
      type: 'file',
      group: 'en',
      options: {
        accept: '.pdf',
      },
      description: 'Optional. If empty, the Spanish PDF will be used for the English site too.',
    }),
    defineField({
      name: 'date',
      title: 'Fecha del Viaje',
      type: 'string',
      group: 'general',
      description: 'Ej: "15 - 16 Octubre" o "Todos los fines de semana"',
    }),
    defineField({
      name: 'price',
      title: 'Precio',
      type: 'string',
      group: 'general',
      description: 'Ej: "Q 450.00"',
    }),
    defineField({
      name: 'duration',
      title: 'Duración',
      type: 'string',
      group: 'es',
      description: 'Ej: "2 Días / 1 Noche"',
    }),
    defineField({
      name: 'durationEn',
      title: 'Duration (English)',
      type: 'string',
      group: 'en',
      description: 'E.g. "2 Days / 1 Night". Optional, falls back to Spanish if empty.',
    }),
    defineField({
      name: 'status',
      title: 'Estado del Tour',
      type: 'string',
      group: 'general',
      options: {
        list: [
          { title: 'Disponible', value: 'disponible' },
          { title: 'Últimos Cupos', value: 'ultimos-cupos' },
          { title: 'Agotado', value: 'agotado' },
        ],
      },
      initialValue: 'disponible',
    }),
    defineField({
      name: 'description',
      title: 'Descripción Corta',
      type: 'text',
      group: 'es',
      rows: 3,
    }),
    defineField({
      name: 'descriptionEn',
      title: 'Short Description (English)',
      type: 'text',
      group: 'en',
      rows: 3,
      description: 'Optional. If empty, the Spanish description will be shown on the English site.',
    }),
  ],
})
